import { User } from './models/user.model';
import { Equipment } from './models/equipment.model';
import { EquipmentRequest } from './models/request.model';

export const MOCK_USERS: User[] = [
  {
    id: 'u0',
    name: 'Admin Système',
    email: 'admin@company.com',
    role: 'admin',
    department: 'IT',
    position: 'Administrateur Système',
  },
  {
    id: 'u1',
    name: 'Alice Martin',
    email: 'alice@company.com',
    role: 'employee',
    department: 'Développement',
    position: 'Développeuse Frontend',
  },
  {
    id: 'u2',
    name: 'Bob Dupont',
    email: 'bob@company.com',
    role: 'employee',
    department: 'Marketing',
    position: 'Chef de Projet',
  },
  {
    id: 'u3',
    name: 'Charlie Bernard',
    email: 'charlie@company.com',
    role: 'employee',
    department: 'Développement',
    position: 'Développeur Backend',
  },
  {
    id: 'u4',
    name: 'Diana Rousseau',
    email: 'diana@company.com',
    role: 'employee',
    department: 'RH',
    position: 'Responsable RH',
  },
  {
    id: 'u5',
    name: 'Eve Leclerc',
    email: 'eve@company.com',
    role: 'employee',
    department: 'Finance',
    position: 'Analyste Financière',
  },
];

export const MOCK_EQUIPMENTS: Equipment[] = [
  {
    id: 'e1',
    name: 'Dell XPS 15',
    category: 'laptop',
    brand: 'Dell',
    serialNumber: 'DLL-001-2023',
    status: 'assigned',
    assignedTo: 'u1',
    purchaseDate: '2023-03-15',
  },
  {
    id: 'e2',
    name: 'MacBook Pro 14"',
    category: 'laptop',
    brand: 'Apple',
    serialNumber: 'APL-002-2023',
    status: 'assigned',
    assignedTo: 'u3',
    purchaseDate: '2023-05-20',
  },
  {
    id: 'e3',
    name: 'HP EliteBook 840',
    category: 'laptop',
    brand: 'HP',
    serialNumber: 'HP-003-2022',
    status: 'available',
    purchaseDate: '2022-11-10',
  },
  {
    id: 'e4',
    name: 'Lenovo ThinkPad X1',
    category: 'laptop',
    brand: 'Lenovo',
    serialNumber: 'LNV-004-2024',
    status: 'available',
    purchaseDate: '2024-01-08',
  },
  {
    id: 'e5',
    name: 'LG UltraWide 34"',
    category: 'monitor',
    brand: 'LG',
    serialNumber: 'LG-005-2023',
    status: 'assigned',
    assignedTo: 'u1',
    purchaseDate: '2023-03-15',
  },
  {
    id: 'e6',
    name: 'Dell UltraSharp 27"',
    category: 'monitor',
    brand: 'Dell',
    serialNumber: 'DLL-006-2022',
    status: 'assigned',
    assignedTo: 'u2',
    purchaseDate: '2022-08-20',
  },
  {
    id: 'e7',
    name: 'Samsung 32" 4K',
    category: 'monitor',
    brand: 'Samsung',
    serialNumber: 'SAM-007-2023',
    status: 'available',
    purchaseDate: '2023-09-01',
  },
  {
    id: 'e8',
    name: 'Logitech MX Keys',
    category: 'keyboard',
    brand: 'Logitech',
    serialNumber: 'LGT-008-2023',
    status: 'assigned',
    assignedTo: 'u3',
    purchaseDate: '2023-06-01',
  },
  {
    id: 'e9',
    name: 'Keychron K2 Pro',
    category: 'keyboard',
    brand: 'Keychron',
    serialNumber: 'KCH-009-2024',
    status: 'available',
    purchaseDate: '2024-02-14',
  },
  {
    id: 'e10',
    name: 'Logitech MX Master 3',
    category: 'mouse',
    brand: 'Logitech',
    serialNumber: 'LGT-010-2023',
    status: 'assigned',
    assignedTo: 'u2',
    purchaseDate: '2022-08-20',
  },
  {
    id: 'e11',
    name: 'Apple Magic Mouse',
    category: 'mouse',
    brand: 'Apple',
    serialNumber: 'APL-011-2023',
    status: 'available',
    purchaseDate: '2023-05-20',
  },
  {
    id: 'e12',
    name: 'Sony WH-1000XM5',
    category: 'headset',
    brand: 'Sony',
    serialNumber: 'SNY-012-2023',
    status: 'assigned',
    assignedTo: 'u1',
    purchaseDate: '2023-03-15',
  },
  {
    id: 'e13',
    name: 'Jabra Evolve2 75',
    category: 'headset',
    brand: 'Jabra',
    serialNumber: 'JBR-013-2022',
    status: 'available',
    purchaseDate: '2022-12-01',
  },
  {
    id: 'e14',
    name: 'iPad Pro 12.9"',
    category: 'tablet',
    brand: 'Apple',
    serialNumber: 'APL-014-2023',
    status: 'available',
    purchaseDate: '2023-10-15',
  },
  {
    id: 'e15',
    name: 'Dell OptiPlex 7090',
    category: 'desktop',
    brand: 'Dell',
    serialNumber: 'DLL-015-2021',
    status: 'maintenance',
    purchaseDate: '2021-06-10',
    notes: 'En réparation — ventilateur défaillant',
  },
];

export const MOCK_REQUESTS: EquipmentRequest[] = [
  {
    id: 'r1',
    employeeId: 'u1',
    category: 'monitor',
    description: 'Second moniteur pour setup dual screen',
    justification: 'Amélioration de la productivité pour le développement frontend',
    status: 'pending',
    requestDate: '2026-04-25',
  },
  {
    id: 'r2',
    employeeId: 'u2',
    category: 'headset',
    description: 'Casque pour réunions Teams/Zoom',
    justification: 'Nombreuses réunions clients par semaine',
    status: 'approved',
    requestDate: '2026-04-10',
    responseDate: '2026-04-12',
    adminNote: 'Approuvé — casque Jabra assigné',
    assignedEquipmentId: 'e13',
  },
  {
    id: 'r3',
    employeeId: 'u3',
    category: 'monitor',
    description: 'Moniteur additionnel',
    justification: 'Besoin de voir frontend et backend simultanément',
    status: 'pending',
    requestDate: '2026-04-26',
  },
  {
    id: 'r4',
    employeeId: 'u4',
    category: 'tablet',
    description: 'Tablette pour présentations RH',
    justification: 'Présentations lors des entretiens et formations',
    status: 'rejected',
    requestDate: '2026-04-01',
    responseDate: '2026-04-03',
    adminNote: 'Refusé — budget non disponible ce trimestre',
  },
  {
    id: 'r5',
    employeeId: 'u5',
    category: 'laptop',
    description: 'Laptop plus performant pour analyses financières',
    justification: 'Traitement de fichiers Excel volumineux ralenti sur machine actuelle',
    status: 'pending',
    requestDate: '2026-04-27',
  },
];
